language: generic

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh

install:
  - evm install $EVM_EMACS --use --skip

env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-git-snapshot-travis
  - EVM_EMACS=remacs-git-snapshot-travis

matrix:
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis
      - EVM_EMACS=remacs-git-snapshot-travis

script:
  - EMACS=`which emacs` ./run_rust_emacs_tests.sh

notifications:
  email: false
